# Generated by Django 4.2.20 on 2025-07-10 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("supplements", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="supplement",
            old_name="reviews_count",
            new_name="review_count",
        ),
    ]
