# Generated by Django 4.2.20 on 2025-07-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplements", "0002_rename_reviews_count_supplement_review_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplement",
            name="title",
            field=models.CharField(max_length=500),
        ),
    ]
