# Generated by Django 4.2.20 on 2025-07-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplements", "0003_alter_supplement_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplement",
            name="product_url",
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="supplement",
            name="title",
            field=models.CharField(max_length=300),
        ),
    ]
