# Generated by Django 4.2.20 on 2025-07-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("supplements", "0004_alter_supplement_product_url_alter_supplement_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplement",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
