# Generated by Django 4.2.20 on 2025-07-17 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="micronutrient_interest",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "None"),
                    ("vitamin a", "Vitamin A"),
                    ("vitamin b1", "Vitamin B1"),
                    ("vitamin b6", "Vitamin B6"),
                    ("vitamin b12", "Vitamin B12"),
                    ("vitamin c", "Vitamin C"),
                    ("vitamin d", "Vitamin D"),
                    ("vitamin e", "Vitamin E"),
                    ("vitamin k", "Vitamin K"),
                    ("calcium", "Calcium"),
                    ("zinc", "Zinc"),
                    ("iron", "Iron"),
                    ("magnesium", "Magnesium"),
                    ("potassium", "Potassium"),
                    ("omega 3", "Omega 3"),
                    ("prebiotic", "Prebiotic"),
                    ("probiotic", "Probiotic"),
                    ("fiber", "Fiber"),
                    ("collagen", "Collagen"),
                    ("creatine", "Creatine"),
                ],
                help_text="Pick a specific micronutrient to prioritize",
                max_length=20,
            ),
        ),
    ]
