# Generated by Django 4.2.20 on 2025-07-18 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommender", "0003_remove_userprofile_micronutrient_interest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="health_goals",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("immunity", "Immunity"),
                        ("muscle", "Muscle Building"),
                        ("bone", "Bone Health"),
                        ("heart", "Heart Health"),
                        ("skin", "Skin Health"),
                        ("sleep", "Sleep Support"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="Select one or more health goals",
                size=None,
            ),
        ),
    ]
