# Generated by Django 4.2.20 on 2025-07-31 05:19

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recommender", "0004_alter_userprofile_health_goals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="dietary_restrictions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("vegetarian", "Vegetarian"),
                        ("vegan", "Vegan"),
                        ("gluten free", "Gluten Free"),
                        ("dairy free", "Dairy Free"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                help_text="Select one or more dietary restrictions",
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="micronutrient_interests",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("", "None"),
                        ("vitamin a", "Vitamin A"),
                        ("vitamin b1", "Vitamin B1"),
                        ("vitamin b6", "Vitamin B6"),
                        ("vitamin b12", "Vitamin B12"),
                        ("vitamin c", "Vitamin C"),
                        ("vitamin d", "Vitamin D"),
                        ("vitamin e", "Vitamin E"),
                        ("vitamin k", "Vitamin K"),
                        ("calcium", "Calcium"),
                        ("zinc", "Zinc"),
                        ("iron", "Iron"),
                        ("magnesium", "Magnesium"),
                        ("potassium", "Potassium"),
                        ("omega 3", "Omega 3"),
                        ("prebiotic", "Prebiotic"),
                        ("probiotic", "Probiotic"),
                        ("fiber", "Fiber"),
                        ("collagen", "Collagen"),
                        ("creatine", "Creatine"),
                        ("protein", "Protein"),
                    ],
                    max_length=20,
                ),
                blank=True,
                default=list,
                help_text="Select one or more micronutrients to prioritize",
                size=None,
            ),
        ),
        migrations.CreateModel(
            name="UserRegimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("supplement_title", models.CharField(max_length=200)),
                ("supplement_brand", models.CharField(blank=True, max_length=100)),
                (
                    "supplement_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("supplement_url", models.URLField(blank=True)),
                ("supplement_category", models.CharField(blank=True, max_length=100)),
                ("dosage", models.CharField(max_length=100)),
                (
                    "timing",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("evening", "Evening"),
                            ("night", "Night"),
                        ],
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regimen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "supplement_title", "supplement_brand")},
            },
        ),
    ]
