# Generated by Django 4.2.20 on 2025-07-31 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recommender", "0005_alter_userprofile_dietary_restrictions_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userregimen",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="userregimen",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
